:project: Les colons de Catane

= Spécification des exigences

== Introduction 

Ce chapitre décrit les exigences du projet «{project}». Il suit la norme IEEE 830-1998.

=== Avant-propos

L'objectif de ce document est de décrire les spécifications des exigences du projet "{project}" pour les étudiants en génie logiciel.

=== Définitions, acronymes et abréviations

Aucune jusqu'à présent.

=== Public visé et suggestions de lecture

Le public visé par cette spécification comprend les développeurs potentiels de l'application, ainsi que les personnes chargées de l'évaluation technique.

=== Portée du projet

Le système logiciel à produire est une version simplifiée du jeu de plateau {project}, qui sera désigné par le terme "{project}" dans le présent document.

Le système {project} permettra à des joueurs de différents endroits de s'affronter dans des parties courtes et intensives.

=== Références

. IEEE Standard 830-1993: IEEE Recommended Practice for Software Requirements Specifications

=== Vue d’ensemble 

Le reste de ce document contient une description globale du système logiciel {project} (section <<description>>, les exigences fonctionnelles spécifiques (section <<fonctional>>) et les exigences non-fonctionnelles du système (voir <<nonfonctional>>.

== Organisation du chapitre

[#description]
== Description générale

=== Perspectives du produit

{project} est un jeu de plateau où plusieurs joueurs s'affrontent.
Le logiciel {project} doit permettre aux joueurs qui sont connectés à Internet d'utiliser leurs appareils connectés pour jouer.
Ainsi, "{project}" est une version électronique en ligne du jeu de plateau.

Bien que le système soit distribué et organisé en différents composants, les joueurs doivent le percevoir comme un seul logiciel.
La figure <<deployment>> présente l'architecture globale du logiciel.
Les joueurs interagissent avec un client Web, qui utilise le protocole HTTP pour communiquer avec (au maximum) un serveur de jeu.
Les serveurs utilisent le protocole TCP/IP pour communiquer avec un serveur de gestion de base de données, qui stocke toutes les données du logiciel.

[#deployment]
.UML Diagramme de déploiement
[plantuml]
....
@startuml
node "Game Server" as server {
    artifact "Spring" as modeA
    artifact "Java" as modeB
}
node "Game Client Nathan" as nathan {
    artifact "Angular" as modeCa
    artifact "TypeScript" as modeDs
}
node "Game Client Rodrigue" as rodrigue {
    artifact "Angular" as modeCqqs
    artifact "TypeScript" as modeDv
}
node "Game Client Erwan" as erwan {
    artifact "Angular" as modeCq
    artifact "TypeScript" as modeDe
}
node "Game Client Bilal" as bilal {
    artifact "Angular" as modeCg
    artifact "TypeScript" as modeDh
}

server -up- nathan : <<protocol>> Web Socket and HTTP
server -down- rodrigue : <<protocol>>  Web Socket and HTTP
server -left- erwan : <<protocol>> Web Socket and HTTP
server -right- bilal : <<protocol>> Web Socket and HTTP
@enduml
....



Ce logiciel est un nouveau produit autonome.

=== Fonctionnalités du produit

Le logiciel {project} doit assurer deux fonctions principales :

. Création de jeu : permettre à quatre joueurs de lancer l'initialisation et de commencer une partie.
. Le jeu{nbsp}: permettre aux joueurs de jouer effectivement à {project} jusqu'à la victoire de l'un d'entre eux.

=== Caractéristiques et classes d'utilisateurs

Le logiciel {project} n'a qu'une seule classe d'utilisateurs : les joueurs.
Les joueurs doivent utiliser la même interface utilisateur pour jouer les uns contre les autres.
Le logiciel ne garde pas trace de l'évolution d'un joueur, du nombre de partie qu'il a joué, etc... et ne permet pas de différencier le niveau des joueurs, par exemple.

=== Environnement opérationnel

Le logiciel {project} doit fonctionner sur tout système d'exploitation populaire et récent{nbsp}: Linux, Windows, ou MacOS.
Le client Web devrait fonctionner sur tout navigateur Web récent{nbsp}: Firefox, Chrome, Safari, ou Edge.

== Contraintes de conception et de mise en œuvre

=== Langages de programmation

. Le serveur de jeu doit être développé en Java (version ≥ 11), en utilisant le https://spring.io [Spring Framework].
. Le client doit être développé en TypeScript (version ≥ 4.0), en utilisant le https://angular.io [Angular Framework].

=== Langage de conception

. Les documents sur le développement du logiciel doivent être écrits dans le format Asciidoc.
. Les diagrammes UML d'analyse, conception et mise en œuvre devront être réalisés en PlantUML.

=== Conception
=== Mise en œuvre

. Les tests dynamiques doivent utiliser JUnit (version >= 5.0) et Jasmine (version >= 3.5.0).
. Le code doit journaliser ses principales opérations en utilisant https://www.slf4j.org [SLF4J].

=== Outils de construction

. Tous les artefacts logiciels doivent utiliser un outil de construction : Maven ou Groovy pour Java, npm pour TypeScript.

=== Outils de développement
=== Bibliothèques et composants logiciels


== Vérification

. Les doubles tests doivent être utilisés pour tester chaque composant indépendamment.
. Chaque test unitaire doit décrire son intention.

== Documentation utilisateur

Aucune documentation utilisateur n'est requise pour la première version du logiciel.

=== Hypothèses et dépendances

Aucune jusqu'à présent.

=== Exigences reportées

Aucune jusqu'à présent.

== Exigences en matière d'interface externe

=== Interfaces utilisateur

[NOTE]
====
Décrivez les caractéristiques logiques de chaque interface entre le produit logiciel et les utilisateurs. 

Il peut s'agir d'exemples d'images d'écran, de normes d'interface graphique ou de guides de style de famille de produits à respecter, de contraintes de disposition des écrans, de boutons et de fonctions standard (p. ex., aide) qui apparaîtront sur chaque écran, de raccourcis clavier, de normes d'affichage des messages d'erreur, etc. 

Définissez les composants logiciels pour lesquels une interface utilisateur est nécessaire. 
Les détails de la conception de l'interface utilisateur doivent être documentés dans une spécification d'interface utilisateur distincte.
====

=== Interfaces matérielles

Le logiciel n'interagit pas directement avec un quelconque dispositif matériel.

=== Interfaces logicielles

La partie client du logiciel doit fonctionner sur des navigateurs web, tandis que la partie serveur doit interagir avec une base de données par le biais de l'API Java Persistence (JPA).

=== Interfaces de communication

Les communications entre le client et le serveur de jeu doivent utiliser des Websockets.

[#features]
== Exigences fonctionnelles

=== Fonctionnalité : Connexion du client au serveur

==== Description et priorité

Le client se connecte au serveur. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le lancement du logiciel par le client. La réponse du serveur sera un message indiquant que la connexion au serveur est en cours.

==== Exigences fonctionnelles

* REQ-1: En cas d'erreur de connexion, le logiciel s'arrête. 

==== Description sous la forme d'un cas d'utilisation

.connexion
include::../partials/uc-connection.adoc[]

=== Fonctionnalité : Création de la partie

==== Description et priorité

Le serveur créé une partie. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le fait qu'il y ait un joueur en attente dans la file d'attente du serveur. La réponse du serveur sera un message indiquant que la création de la partie est en cours.

==== Exigences fonctionnelles 

* REQ-1: En cas d'erreur dans la création de la partie, un message d'erreur est affiché pour le client

==== Description sous la forme d'un cas d'utilisation
.création de la partie
include::../partials/uc-createGame.adoc[]

=== Fonctionnalité : Rejoindre une partie
Un client demande au serveur de le placer dans une partie.

==== Description et priorité

Le serveur place le client dans une partie déjà créée. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le fait qu'il y ait au moins une partie créée en attente d'initialisation ayant moins de quatre joueurs. La réponse du serveur sera un message indiquant que l'incorporation du joueur à la partie est en cours.

==== Exigences fonctionnelles 

* REQ-1: En cas d'erreur dans l'incorporation du joueur à la partie, un message d'erreur est affiché pour le client

==== Description sous la forme d'un cas d'utilisation

.Rejoindre une partie
include::../partials/uc-gameJoin.adoc[]

=== Fonctionnalité : Initialisation de la partie

Met en place la partie afin qu'elle puisse débuter.

==== Description et priorité

Le serveur exécute la commande d'initialisation de la partie. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le fait qu'il y ait quatre joueurs dans une partie en attente d'initialisation. La réponse du serveur sera un message indiquant que l'initialisation de la partie est en cours.

==== Exigences fonctionnelles 

* REQ-1: En cas d'erreur dans l'initialisation de la partie, un message d'erreur est affiché pour le client

==== Description sous la forme d'un cas d'utilisation
.Initialisation de la partie
include::../partials/uc-initGame.adoc[]

=== Fonctionnalité : Commence la partie
le serveur met en place les conditions nécessaires pour que le premier tour du jeu puisse commencer.

==== Description et priorité

Le serveur exécute les commandes nécessaires au commencement de la partie. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le fait qu'il y ait quatre joueurs dans une partie initialisée. La réponse du serveur sera un message indiquant que la préparation de la partie est en cours.

==== Exigences fonctionnelles 

* REQ-1: En cas d'erreur dans le commencement de la partie, un message d'erreur est affiché pour le client

==== Description sous la forme d'un cas d'utilisation
.Commence la partie
include::../partials/uc-startGame.adoc[]

=== Fonctionnalité : Jouer un tour
Un client joue un tour de jeu complet.

==== Description et priorité

Le client envoie les différentes commandes d'actions de jeu selon si il peut et veut les utiliser. Cette fonctionnalité a une priorité élevée.

==== Séquences de Stimulus/Réponse

Le stimulus de cette fonctionnalité est le fait qu'il y ait quatre joueurs dans une partie demarrée. La réponse du serveur sera un message indiquant que l'initialisation de la partie est en cours.

==== Exigences fonctionnelles

* REQ-1: En cas d'erreur dans un tour d'un joueur de la partie, un message d'erreur est affiché pour le client

==== Description sous la forme d'un cas d'utilisation
.Jouer un tour
include::../partials/uc-playTurn.adoc[]

[#nonfunctional]
== Autres exigences non-fonctionnelles

=== Exigences de performance 

. Le jeu doit être _jouable_, ce qui signifie que les utilisateurs doivent avoir un retour rapide de leurs actions et que les retards dus aux problèmes de communication/connexion doivent être correctement tenus.
. Le client Web doit pouvoir s'exécuter sur un ordinateur personnel doté de 4 Go de RAM.


=== Exigences de sécurité

Aucune pour le moment.

=== Attributs de qualité logicielle

Pour les clients, le logiciel doit être facile à utiliser et fluide dans son exécution. +
Pour les développeurs, le code doit avoir un couplage faible et une excellente maintenabilité.

==== Extensibilité

. Le logiciel doit pouvoir permettre d'envisager l'implémentation des extensions de {project}, notamment dans le futur.

==== Maintenabilité

. Le logiciel doit être lisible et facile à maintenir.
. Le code source Java doit respecter les directives de Google : https://google-styleguide.googlecode.com/svn/trunk/javaguide.html.

=== Règles métier

Il n'y a pas de règles métier pour ce projet.

== Autres exigences

Aucune pour le moment.

=== Annexe A : Modèles d'analyse

Voir le chapitre <<domain>> (analyse du domaine) pour plus de détails.
