:project: Les colons de Catane
= Architecture

== Introduction

[NOTE]
====
Le but de ce chapitre est de spécifier l'architecture d'une famille de produits,
dont le projet {project} en fait partie.

Il s'agit ici de choix génériques, qui peuvent s'appliquer à plusieurs projets.
====
Vous pouvez retrouver dans cette partie, l'ensemble des principes d'architectures que nous allons utiliser.
Des librairies utilisés, en passant par les différents nœuds logiques, vous pouvez observer comment le serveur est gérer au niveau de son architecture.

== Vue physique

[NOTE]
====
La vue physique a pour but de décrire comment devrait être déployé le logiciel selon des nœuds logiques.
Ainsi que de définir comment ou plutôt par quel moyen les différents nœuds vont communiquer entre eux.
Et enfin le dernier but de cette vue est de donner les différentes contraintes de déploiement,
comme quelles librairies sont utilisées, quels sont les besoins matériels.
====

Au niveau de la vue physique, on retrouve donc 2 nœuds logiques qui sont :

* Game Server
* Game Client

Ainsi ces 2 nœuds vont devoir comuniquer et différents protocols vont être utilisé.
Ces 2 nœuds ne peuvent pas être réduit, on retrouvera forcément un serveur qui gère les parties, évite qu'il y ait de la fraude et des clients qui font office de passerelles entre le joueur (Personne physique) et le jeu (logiciel).
On note pour le serveur, l'utilisation de Java Spring pour la gestion des sockets ainsi que le protocole HTTP pour la première connexion du client.
On peut voir l'utilisation des 2 protocols coté serveur via ce diagramme de séquence :

include::sequenceDiagram_Protocols.adoc[]


Le noeud logique Game Client utilise TypeScript ainsi que le framework Angular pour gérer l'affichage au sein d'un navigateur web.

Les dépendances principales sont :

* angular
* rxjs
* tslib
* zone.js

.Exemple d'un diagramme de déploiement (niveau spécification)


include::deploymentDiagram.adoc[]

.Exemple d'un diagramme de déploiement (niveau instance)

include::deploymentDiagramInstance.adoc[]

Ainsi, on peut voir que chaque nœuds Client est "dupliqué", on retrouve les mêmes librairies, les mêmes composants, les mêmes protocols.
Pour les clients, on retrouve Angular qui gère l'interface utilisteur et Typescript qui s'occupe de la communication avec le serveur.
Pour l'exemple, il y a 4 clients qui est le nombre maximal de joueur pour une seule partie.
Sur le diagramme, un seul lien relie chaque client au serveur, mais c'est bien un lien différent pour chaque protocol (HTTP et WebSocket).


== Vue de la fiabilité

[NOTE]
====
Dans cette partie, vous allez présenter les différents choix architecturaux pour assurer la fiabilité du système.

Vous devez aussi présenter les prévisions de fonctionnement dans des conditions limite{nbsp}:
* Comment le système est initialisé{nbsp}?
* Comment le système est arrêté{nbsp}?
* Comment sont gérés les failles et le redémarrage du système{nbsp}?
====

[TIP]
====
Utilisez des diagrammes d'activité UML pour décrire l'initialisation et l'arrêt du système.
====

=== Prévisions de fonctionnement
==== INITIALISATION DU SYSTEME : 
Un client exécute le logiciel. Si le serveur est éteint, il s'allume.

==== ARRET DU SYSTEME : 
Une fois que toutes les parties se déroulant sur le serveur sont terminées et qu'il n'y a plus de clients en attente de parties, le serveur s'arrête jusqu'à la prochaine exécution du logiciel par un client.

==== GESTION DES FAILLES ET DU REDEMARRAGE DU SYSTEME : 
En cas d'arrêt non souhaité du serveur, par exemple avec une panne du serveur, le serveur est relancé, les parties sont détruites et les clients de la partie encore connectés sont remis dans la file d'attente des participants. +
En cas d'arrêt inattendu d'un client jouant à une partie en cours, cette partie se termine immédiatement puis elle est détruite et les clients de la partie encore connectés sont remis dans la file d'attente des participants. Le client qui s'est arrêté devra ré-exécuter le logiciel pour se connecter de nouveau au serveur. +
Si c'est le système entier qui s'arrête inopinément, un client devra l'exécuter à nouveau pour relancer le système. +

.Diagramme d'activité de l'initialisation du système

include::initializationSystemActivityDiagram.adoc[]

.Diagramme d'activité de l'arrêt du système

include::systemStopActivityDiagram.adoc[]


== Vue du développement

[NOTE]
====
Décrivez ici l'organisation du code source.
Plutôt que décrire les paquetages Java ou Typescript, décrivez plutôt les artefacts Maven et les modules Node.js.
====


[TIP]
====
Utilisez un https://www.uml-diagrams.org/package-diagrams-overview.html[Diagramme de paquetages]
pour décrire l'organisation du code source.
====

.Organisation des modules
include::packageDiagram.adoc[]




== Vue logique

.Diagramme de composants de la vue logique
[plantuml]
....
@startuml
left to right direction

[Server]
[Client]
[Middleware]

[Middleware] - ServerToClientServer : "\t\t"
ServerToClientServer )- [Server] : "\t\t"
[Server] - ClientToServerServer : "\t\t"
ClientToServerServer )- [Middleware] : "\t\t"

[Middleware] - ClientToServerClient : "\t\t"
ClientToServerClient )-up- [Client] : "\t\t"
[Client] - ServerToClientClient : "\t\t"
ServerToClientClient )- [Middleware] : "\t\t"
@enduml
....


== Vue des processus

[plantuml]
....
@startuml
package ProcessusServer{
	package ThreadSpring{
		JavaSpring : Ecoute des sockets ...
	}
	
	package ThreadPrincipal{
		serverMain : GameManager
	}
	
	package ThreadN{
		GameControlerN : La n-ième Game.
	}
}
@enduml
....


== Vue technique : traduction de UML en code source

Nous allons simplement nous répartir le travail pour que chacun code une partie du projet.
L'idéal serait que tout le monde "touche à tout" et donc il serait interessent de ne pas distribuer simplement chaque classe à chacun.



=== Règles de traduction des types de base

.Traduction des types de base
|===
| UML | Java | TypeScript

| Integer
| int
| number

| Boolean
| bool
| boolean

| String
| String
| string

| Real
| double
| number

|===

D'après : https://www.typescriptlang.org/docs/handbook/basic-types.html

=== Conventions de codage

Ce projet respecte les conventions JAVA distribuées par Oracle. Cela nous permet d'affirmer que notre code est "propre" selon les normes java présentes à cette adresse : https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html.

=== Règles de traduction des composants

Du côté serveur, on se retrouver avec 2 composants dont un qui ne sera pas codé qui est JavaSpring.
Le composant principal que nous nommons Server est l'ensemble des GameManager, GameControler, GameFacade... 

Du côté client, on va également se retrouver avec 2 composants dont un qui ne sera aussi pas codé et qui gère les webSockets, il n'a pas de nom.
On va devoir également coder le composant principal que nous nommons, incroyable nom, Client qui regroupe l'ensemble des GameManager, GameControler, GameFacade...

=== Règles de traduction des classes

Nous allons interpreter les diagrames UML tout simplement avec un package donne un package, une classe donne une classe...
Chaque classe utilisera une référence à une interface et non une classe pour minimiser le couplage.
[plantuml]
....
@startuml
package test{
	interface Test{}
	class TestImpl extends Test{}
}
@enduml
....

Ainsi, on va se retrouver avec un manager, ce dernier permet coté serveur de gérer l'ensemble des parties et de faire le lien entre ces dernières et Java Spring, et du coté client de faire le lien entre la librairie de websocket et la partie.
Pour la partie, c'est le contrôleur qui va gérer cela, faire le lien entre le NetworkControler, la GameFacade et la CommandFactory.

* NetworkControler : Le contrôleur qui s'occupe de la partie réseau, avec ce dernier, aucune commande ni ressource du GameControler ne sort.
* GameFacade : Du design pattern Facade, cette classe permet de faire le lien entre le GameControler et le package du jeu. Cela permet de minimiser le couplage.
* CommandFactory : Du designPattern Factory, cette classe permet de fabriquer les Commands (cf Conception). 

=== Règles de traduction des associations

Les associations entre les classes / interfaces, sont assez simple : 

[plantuml]
....
@startuml
interface Test{}
class Test2 {}
note top : Test2 is composed of 1 Test

Test2 *-- Test

interface Test3{}
class Test4 {}
note top : Test4 is composed of 3-4 Test3

Test4 *-- "3-4" Test3
@enduml
....
Ainsi lorsqu'il n'y a pas de cardinalité, c'est qu'il y a une association de 1 pour 1.
Quoi qu'il arrive, dans notre serveur, il n'y aura qu'un seul GameManager et autant de GameControler qu'il y a de partie.

== Conclusion

Ceci est une conclusion hative; bien qu'elle existe, elle ne doit pas être utilisée dans un quelconque but de productivité ou de compréhension de ce projet. Nous remercions tous nos proches d'avoir pu contribuer de près ou de loin à ce fabuleux et merveilleux projet. :) Voilà merci à toutes et à tous. Bisouuuuuh UwU. A REVOIR /!\
