:project: Les colons de Catane
= Architecture

== Introduction

[NOTE]
====
Le but de ce chapitre est de spécifier l'architecture d'une famille de produits,
dont le projet {project} en fait partie.

Il s'agit ici de choix génériques, qui peuvent s'appliquer à plusieurs projets.
====

== Vue physique

[NOTE]
====
La vue physique a pour but de décrire comment devrait être déployé le logiciel selon des nœuds logiques.
Ainsi que de définir comment ou plutôt par quel moyen les différents nœuds vont communiquer entre eux.
Et enfin le dernier but de cette vue est de donner les différentes contraintes de déploiement,
comme quelles librairies sont utilisées, quels sont les besoins matériels.
====

[NOTE]
====
Pour décrire la vue physique, vous allez vous appuyer sur deux diagrammes{nbsp}:

. Le diagramme de déploiement, qui ci doit expliquer la plupart des points énoncés précédemment.
. Le diagramme de déploiement au niveau des instances, qui respecte les spécifications du diagramme précédent,
pour montrer comment seront réparties les instances de ceci.
====

.Exemple d'un diagramme de déploiement (niveau spécification)
[plantuml]
----
include::deployment.adoc[]
----

[NOTE]
====
Décrivez les nœuds logiques, ainsi que les artefacts qui peuvent être déployés sur ces nœuds.
Vous pouvez profiter de ce diagramme pour expliquer le protocole de communication entre les nœuds.
====

.Exemple d'un diagramme de déploiement (niveau instance)
[plantuml]
----
include::deploymentInstance.adoc[]
----

[NOTE]
====
Expliquez ce diagramme, si les artefacts déployés sont différents, vous pouvez le montrer.
====

== Vue de la fiabilité

[NOTE]
====
Dans cette partie, vous allez présenter les différents choix architecturaux pour assurer la fiabilité du système.

Vous devez aussi présenter les prévisions de fonctionnement dans des conditions limite{nbsp}:
* Comment le système est initialisé{nbsp}?
* Comment le système est arrêté{nbsp}?
* Comment sont gérés les failles et le redémarrage du système{nbsp}?
====

[TIP]
====
Utilisez des diagrammes d'activité UML pour décrire l'initialisation et l'arrêt du système.
====

.Initialisation du système
[plantuml]
----
include::example$ad-initialization.plantuml[]
----

== Vue du développement

[NOTE]
====
Décrivez ici l'organisation du code source.
Plutôt que décrire les paquetages Java ou Typescript, décrivez plutôt les artefacts Maven et les modules Node.js.
====


[TIP]
====
Utilisez un https://www.uml-diagrams.org/package-diagrams-overview.html[Diagramme de paquetages]
pour décrire l'organisation du code source.
====

.Organisation des modules
[plantuml]
----
include::example$pd-example.plantuml[]
----




== Vue logique

[NOTE]
====
L'objectif de la vue logique est de décrire les différents composants qui jouent un rôle commun
dans les différents projets qui respectent une même architecture.
====


== Vue des processus

[NOTE]
====
TODO!
====


== Vue technique : traduction de UML en code source

[NOTE]
====
Expliquez, dans cette section, l'ensemble de règles que vous utiliserez par la suite pour traduire les
diagrammes de conception UML en code source Java et TypeScript.
====



=== Règles de traduction des types de base

.Traduction des types de base
|===
| UML | Java | TypeScript

| Integer
|
|

| Boolean
|
|

| String
|
|

| Real
|
|

|===

=== Conventions de codage

Ce projet respecte les conventions JAVA distribuées par Oracle. Cela nous permet d'affirmer que notre code est "propre" selon les normes java présentes à cette adresse : "https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html".

=== Règles de traduction des composants

NOTE: Explique ici les règles que vous allez utiliser pour mettre en œuvre les composants UML.

=== Règles de traduction des classes

NOTE: Explique ici les règles que vous allez utiliser pour mettre en œuvre les classes UML.

=== Règles de traduction des associations

NOTE: Expliquez ici les règles qui vous devrez  suivre pour mettre en œuvre les associations,
agrégations composites et agrégations partagées.


== Conclusion

Ceci est une conclusion hative; bien qu'elle existe, elle ne doit pas être utilisée dans un quelconque but de productivité ou de compréhension de ce projet. Nous remercions tous nos proches d'avoir pu contribuer de près ou de loin à ce fabuleux et merveilleux projet. :) Voilà merci à toutes et à tous. Bisouuuuuh UwU. 