@startuml
node "Game Server" as server {
    artifact "Module A" as modeA
    artifact "Module B" as modeB
}
node "Game Player" as player {
    artifact "Module C" as modeC
    artifact "Module D" as modeD
}
server "[1]" -- "[*]" player : <<protocol>> Web Sockets
@enduml