@startuml
package client {
    package core {
        package game {
        	   interface Player{}
            interface GameFacade {
	        	trade(Player, Resource[], Player, Resource[])
	        	addResourcesTo(Player, Resource[])
	        	removeResourcesTo(Player, Resource[])
            }
        }
        package commands {
            interface CommandGameFactory {
            	ActivateThieve(Player[]) : Command
            	MoveThieve(Player[], Coordinates) : Command
            	Ping(Player[]) : Command
            	Build(Player[], Building) : Command
            	ActiveCard(Player[], Card) : Command
            	AddCard(Player[], Player, Integer) : Command
            	BuyCard(Player[], Resource[]) : Command
            	StartTurn(Player[], Player) : Command
            	EndTurn(Player[], Player) : Command
            	TradeWithNonPlayerEntity(Player, Resource[], Resource[] ) : Command
            	TradeWithPlayer(Player, Resource[], Player, Resource[]) : Command
            	DenyTrade(Player, Player) : Command
            	AcceptTrade(Player, Player) : Command
            }
            interface Command {
                execute()
                getRecipients() : Player[]
            }

            interface Serializer {
                serialize(Command): String
                deSerialize(String): Command
            }
        }

        package networking {
            interface ConnectionHandler {
                sendCommand(Command)
                isEnabled(): Boolean
                addServer(Login)
            }
        }

        package controler {
            interface NetworkControler {
            	sendCommand(Command)
            	addServer(Login)
            }
            note right: Network management "module"

            interface GameControler{
                receiveCommand(Command)
                addServer(Login)
                
            	ActivateThieve()
            	MoveThieve()
            	Ping()
            	Build()
            	ActiveCard()
            	AddCard()
            	BuyCard()
            	EndTour()
			TradeWithNonPlayerEntity()
            	TradeWithPlayer()
            	DenyTrade()
            	AcceptTrade()
            }

        }

    }
      
    package clientImpl {
        package commandsImpl {
            class SerializerImpl <<Serializer>>{}
            abstract CommandAbstract <<Command>>{
            }
            note right of CommandAbstract
            		Represent all types of commands.
            end note
            class CommandGameFactoryImpl <<CommandGameFactory>>{}

            CommandAbstract *-up- "1-4"  Player
        }

        package networkingImpl {
            class WebSocketAdapterImpl <<ConnectionHandler>>{
               server: Socket
            }
            class NetworkControlerImpl <<NetworkControler>>{}

            
            NetworkControlerImpl *-up- ConnectionHandler
		   
        }
        package controlerImpl {

            class GameControlerImpl <<GameControler>>{
                me : Player
                commands: Command[]
            }
            GameControlerImpl *-up- "1" CommandGameFactory
            GameControlerImpl *-up- "1" NetworkControler
            GameControlerImpl *-up- "1" GameFacade
            GameControlerImpl *-up- "1" Serializer
            GameControlerImpl *-up- "3-4" Player
            
        }
    }
 
    
    package managment{
    	package api{
    		interface CommandLoginFactory{
	    		createCommandLogin(Content) : Command
	    	}
	    	note right : The login of the server
    	}
    	
    	package managmentImpl{
    		class CommandLoginFactoryWebSocket <<CommandLoginFactory>>{}
    		
		    
		    class ClientGameManager{
		    	createTheParty()
		    	connectServer(Command)
		    }
			
		    class Client {
		        main()
		    }
		    
		    ClientGameManager "1" *-up- "*" GameControler
		    ClientGameManager "1" *-up- "1" CommandLoginFactory
		    Client "1" *-up- "1" ClientGameManager
    	}
    
    }


}
@enduml
