Les différents packages
=======================

* Networking : La partie réseau avec les communications entre clients et serveur.
* Controler : Les contrôleurs (ou modules) de l'application, un pour chaque partie.

Un serveur se compose d'un contrôler de Client (ControlerClient) qui possède plusieurs modules (un par partie) c'est-à-dire : 
un contrôler de jeu (ControlerGame) et un contrôler de jeu (ControlerNetwork).
L'intêret est de séparer chaque partie du serveur pour éviter se retrouver avec une super classe Serveur qui contient des appels dans tous les sens de réseau, de jeu ...
 
[plantuml]
....
@startuml
package Client {
	class Client{
		main() : void
	}
  
  package Commons{
    
  }
  
  package Core {
    package Commands {
      interface CommandFactory{
      	createCommand(type) : Command
      }
      interface Command {
        execute(): void
      }
      
      abstract CommandAbstract {
      		controler : ControlerGame
      		Sender : String
      		Reciever : String
      }
      note bottom: All commands extend from this class
      Command <|--- CommandAbstract
      
    }

    package Networking {
      interface ConnectHandler {
        sendMessage(): void
        isEnabled(): Boolean
      }
		interface WebSocketAdapter {}
		ConnectHandler <|--- WebSocketAdapter
    }
    
    package controler{
    	interface ControlerNetwork{}
    	note top : Network management "module"
    	
    	interface ControlerGame{
    	}
    	note top : Game management "module"
    }

  }

  package ClientImpl {
  package CommandsImpl {
      abstract CommandFactoryImpl{}
      abstract Trade {}
      Trade <|--- TradeWithPlayer
      Trade <|--- TradeWithNonPlayerEntity
      Trade <|--- AcceptTrade
      class TradeWithPlayer {}
      class TradeWithNonPlayerEntity {}
      class AcceptTrade {}
      class BuyCard {}
      class MoveThieve {}
      class Build {}
      class ActiveCard {}
      class Ping {}
      class ActivateThieve {}
      class Victory {}
      class SetResources{}
      class End{}
      
    }
    
  package NetworkingImpl {
    	
      class WebSocketAdapterImpl {}
      
    }
  	package controlerImpl {
  		class ControlerClient{
  		receivedCommands : List<Command>
    	toSendCommands : List<Command>
  		receiveCommand(Command) : void
  		sendCommand(Command) : void
  		getNextCommandToExecute() : Command
  		getNextCommandToSend() : Command
  		}
  		note left : Client management "module"
  		
  		class ControlerNetworkImpl{}
    	
    	class ControlerGameImpl{
    		players : List<Player>
    	}
    	
    	
    	
    	
    	ControlerNetworkImpl ..> WebSocketAdapterImpl : use
    	ControlerGameImpl ..> GameImpl : use
    	
    	ControlerClient *-- ControlerNetworkImpl
    	ControlerClient *-- ControlerGameImpl
    	ControlerClient *--	 CommandFactoryImpl
    	
  	}
    

    

    package GameImpl {}

  }

}

package Client {}
@enduml
....