= Conception détaillée

== Travail à réaliser

// ainsi que de décrire comment vous répondez aux différentes exigences non-fonctionnelles.

Objectif::
Spécification détaillée des composants: leur structure (diagramme de classes de conception), ainsi que le comportement de chaque opération fournie par le composants. Le comportement peut-être décrit en utilisant les diagrammes d'activité, d'interaction, les machines d'état, ainsi que OCL.

Moyens::
Appliquez les concepts vus en cours: design patterns, principes GRASP, bonnes pratiques, etc.


== Réponses aux exigences non-fonctionnelles


=== Concurrence

4 joueurs doivent pouvoir être connectés simultanément à une partie afin qu'elle se déroule correctement. Au moins 2 parties doivent pouvoir se passer en même temps.

=== Performance

Le logiciel doit s'exécuter de manière rapide et fluide tout au long de chacun de ses cycles de vie.

=== Interopérabilité

Le faible couplage du logiciel, obtenu grâce à l'utilisation de nombreuses interfaces permet à notre système d'avoir une forte interopérabilité.

=== Portabilité

Pour l'instant, le jeu est uniquement disponible sur navigateur.

=== Sécurité

Pour l'instant il n'y a pas vraiment de sécurité au niveau de la connexion. Quant au serveur, lui, s'il reçoit des commandes d'un autre joueur alors que ce n'est pas son tour, la commande est annulé, de même quand la commande est impossible (proposition de ressources non valide ...). 

==== Exigence de sécurité

Notre système doit être sécurisé, même si nous ne manipulons pas des données sensibles. Pour cela nous devons vérifier l'identité de l'utilisateur.


N'ayant pas à nous occuper de l'authentification de l'utilisateur nous admettons que le système s'occupant de cela est correct et lui-même sécurisé. Nous admettons également que, quelle que soit la plateforme utilisée (web, logiciel, application) le service d'authentification sera le même pour tous.


==== Maintenabilité

L'architecture de notre logiciel divisée en compartiments et en sous-compartiments nous offre une grande maintenabilité pour les changements futurs éventuels.

=== Interface utilisateur

NOTE: TODO!


=== Interface ou protocoles de communication

Nous utilisons websocket sur lequel nous envoyons des commandes serialize en JSON
(voir command pattern plus bas). Le client et le serveur doivent savoir quelle classe instancier 
a la reception d'une commande. On ajoute un paramètre "type" dans la commande serialize
et nous définissons un mapping commun entre le client et le serveur.
Pour ce faire, on définit le nom des commandes suivantes:

|====
|   ActivateThieve
|   MoveThieve
|   Ping
|   Build
|   ActiveCard
|   AddCard
|   BuyCard
|   EndTurn
|   StartTurn
|   Win
|	SetResources
|	AddResources
|	TradeWithNonPlayerEntity
|	TradeWithPlayer
|	DenyTrade
|	AcceptTrade
|	LoginComplete
|	SetGame
|	SetPlayer
|====

=== Correction

Nous comptons mettre en place une méthode fonctionnelle et une méthode structurelle dnas le but d'élaborer des scénarios de tests afin de nous assurer que notre code est correct.

== Patrons logiciels utilisés

=== Patron de conception Commandes

Nous utilisons le patron Commandes qui permet à au client et au serveur d'avoir un objet de communication.
Ainsi le client (le joueur), lorsque c'est à lui de jouer peut émettre des commandes et ainsi communiquer avec le serveur.
Chaque commande a une implémentation (un comportement précis) et cela permet au serveur de savoir quoi faire.

[plantuml]
....
include::classDiagramCommands.plantuml[]
....

=== Explications des différentes commandes :

[options="header"]
|=======================
|Commande |Explications      
|ActivateThieve    |Choix de la nouvelle position du voleur par le joueur.    
|MoveThieve    |Déplacer le voleur vers une certaine tuile.
|Ping    |Permet au server de verifier si le joueur n'est pas déconnecté.
|Build    |Placer un nouveau batiment pour un joueur.
|ActiveCard    |Activer une carte.
|AddCard    |Ajouter une carte pour un joueur
|BuyCard    |Acheter une carte.
|StartTour    |Indique au joueur que c'est à lui de jouer.
|EndTour    |Mettre fin au tour du joueur actif.
|Win    |Déclarer la victoire d'un joueur.
|SetResources    |Saisir le nombre de ressources d'un joueur.
|AddResources    |Distribuer des ressources à un joueur.
|TradeWithNonPlayerEntity    |Proposition d'échange entre un joueur et une entité non joueur (banque ou port).
|TradeWithPlayer    |Proposition d'échange entre deux joueurs. 
|DenyTrade    |Refuser l'échange d'un autre joueur.
|AcceptTrade    |Accepter l'échange d'un autre joueur.
|LoginComplete    |Indiquer au client qu'il est bien login.
|SetGame    |Saisir l'état actuel de la partie. Envoyée une fois par le serveur au début de la partie.
|SetPlayer    |Dire au client qu'elle est le joueur qu'il joue (=> lui indiquer sa couleur).
|=======================

=== Patron de conception Facade

Ce design pattern va nous permettre d'avoir une classe qui fait le lien entre le serveur et le package qui implémente le jeu.
Cela va permettre dans une version future, de pouvoir changer l'implémentation du jeu sans changer le serveur.

=== Patron de conception Factory

La factory va nous permettre d'avoir une classe qui permet d'instancier les commandes (cf: Design pattern Commandes).

=== Patron de conception Observateur

L'interêt de l'observateur c'est comme son nom l'indique d'observer. Ainsi, en considérant l'interface graphique comme un observer, elle ne va jamais impacter et avoir le moindre effet de bord sur le jeu. De plus, grâce à la méthode notifyObservers(), l'interface graphique sera mise à jour uniquement lorsqu'il y aura des changements. 

== Choix techniques - Distribution des processus

Pour cela nous allons donc vous présenter l'environnement général de développement.

Nous avons fait le choix d'utiliser comme environnement de travail l'IDE IntelliJ.
Pour la raison que nous connaissons tous très bien cet environnement, ce qui nous permet d'avoir tous le même environnement de développement.

Également, cette IDE permet la gestion d'un projet maven ce qui nous sera parfaitement adapté.

== Diagrammes de classes

=== Indications de notations
[plantuml]
....
include::classDiagramIndications.plantuml[]
....

== Server

[plantuml]
....
include::classDiagramServer.plantuml[]
....

=== CameControllerServer

[plantuml]
....
include::classDiagramGameControlerServer.plantuml[]
....

== Client

[plantuml]
....
include::classDiagramClient.plantuml[]
....

=== CameControlerClient

[plantuml]
....
include::classDiagramGameControlerClient.plantuml[]
....
