= Spécification des composants

== Travail à réaliser

Objectif::
Découpage de la solution en composants (ou sous-systèmes) et spécification des interfaces fournies et requises par ces composants

Moyens::
Utilisez des diagrammes d'interaction (séquence, communication) pour décrire l'échange de messages entre les composants pour en déduire leurs interfaces.


.Diagramme de composants
[plantuml]
....
include::example$components.puml
....


.Autre diagramme
[plantuml]
....
@startuml
'https://plantuml.com/component-diagram


package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}

node "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
}

cloud {
  [Example 1]
}


database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}


[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]
[Folder 3] --> [Frame 4]

@enduml


@startuml
[Server]
[Rest (Middleware)]
[WebSocket (Middleware)]
[WebSocket server (Proxy)]
[Client]

DataAccess - [Server]
[WebSocket (Middleware)] ..> DataAccess : use
[Rest (Middleware)] ..> DataAccess : use
DataAccess2 - [WebSocket (Middleware)]
DataAccess3 - [Rest (Middleware)]
[WebSocket server (Proxy)] ..> DataAccess2 : use
DataAccess4 -[WebSocket server (Proxy)]
[Client] ..> DataAccess4 : use

[Server] ..> DataAccess5 : use
DataAccess5 - [Client WS (Proxy)]

[Client WS (Proxy)] ..> DataAccess6 : use
DataAccess6 - [Web socket Client (M:MiddleWare)]

[Web socket Client (M:MiddleWare)] ..> DataAccess7 : use
DataAccess7 - [Client]

@enduml
....
