@startuml

node Client {
    artifact WebClient
}
node Server {
    artifact GameServer
}

node Database {
    artifact DBMS
}

WebClient -left- Server : TCP/IP - WebSockets
Server -up- Database : JPA

@enduml